import Head from "next/head";
import { useState } from "react";
import Expenses from "../components/Expenses";
import MonthBar from "../components/MonthBar";
import NewExpense from "../components/NewExpense";

export default function Home() {
  const [expenses, setExpenses] = useState([]);
  const [currentYear, setCurrentYear] = useState("2020");

  //
  function addToCollection(expense) {
    setExpenses((state) => [...state, expense]);
  }
  // getting each year in month format and calculating the percentage of each month
  const months = [
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
  ];
  const eachYearMonthlyExpenses = expenses.reduce((acc, curr) => {
    const year = curr.date.split("-")[0];
    const month = curr.date.split("-")[1];
    if (!acc[year]) {
      acc[year] = {};

      months.forEach((month) => {
        acc[year][month] = 0;
      });
    }
    acc[year][month] += +curr.amount;
    return acc;
  }, {});

  const monthData = months.map((month) => {
    const filteredExpenses = expenses.filter(
      (expense) => expense.date.split("-")[1] === month
    );
    let total = filteredExpenses.reduce((acc, curr) => {
      return acc + +curr.amount;
    }, 0);
    let posandage = (total / expenses.length) * 100;
    if (Number.isNaN(posandage)) posandage = 0;
    posandage = posandage.toFixed(0);
    return { month, posandage };
  });

  console.log(monthData);
  console.log(eachYearMonthlyExpenses);
  return (
    <div className="">
      <Head>
        <title>expense</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-800 h-full pb-4">
        <main className="md:mx-auto max-w-2xl pt-4 ">
          <NewExpense
            addToCollection={addToCollection}
            currentYear={currentYear}
          />
          <div className="filter p-4 max-w-2xl bg-gray-700 text-white capitalize font-semibold rounded">
            filter by year
            <select
              className="ml-10 text-purple-900 rounded-sm px-4 py-2"
              onChange={(e) => setCurrentYear(e.target.value)}
            >
              <option value="2022">2022</option>
              <option value="2021">2021</option>
              <option value="2020">2020</option>
              <option value="2019">2019</option>
            </select>
          </div>
          <div className="flex justify-around">
            {monthData.map((month) => (
              <MonthBar
                key={month.month}
                month={month.month}
                posandage={month.posandage}
              />
            ))}
          </div>
          <Expenses expenses={expenses} />
        </main>
      </div>
    </div>
  );
}
// calculate totalExpenses and have a deault value of 1
//  dose it need to be in index.js ? no
// where to put it ? on click
//needs acsses to currentYear
//month bar needs access currentYear and totalExpenses
