import Head from "next/head";
import Expenses from "../components/Expenses";
import MonthBar from "../components/MonthBar";
import NewExpense from "../components/NewExpense";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>expense</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-800 h-screen">
        <main className="md:mx-auto max-w-2xl pt-4">
          <NewExpense />

          <MonthBar />
          <Expenses />
        </main>
      </div>
    </div>
  );
}
